### ISSUE TITLE
Passing argument

### ISSUE THREAD

**Issue by ritz078** [chliebel/angular2-click-outside#1]
What if I want to access the event inside my function `close()` ? How can I do it ? What modifications are needed ?

**Comment by christianliebel** [comment]
Sure, this is possible. The event emitter must be of `EventEmitter<MouseEvent>` type. Next, we have to pass the MouseEvent as a parameter to the `onClick` function (pass `$event` instead of or additional to `$event.target` and update usages accordingly). Finally, pass the MouseEvent as an argument when calling `emit` (instead of null). Do you want to try that for yourself and issue a PR or should I introduce this for you? Thanks in advance.

**Comment by christianliebel** [comment]
@ritz078: Since I didn’t hear anything from you, I implemented this functionality in 42a250c7787fcc2683d213ef32667d7fd7c2ac74. Thus, this issue should be closed.
